name: oc_projet9

services:
  redpanda:
    build:
      context: ./redpanda
    container_name: redpanda
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --smp
      - "1"
      - --memory
      - 1G
      - --node-id
      - "0"
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda:33145
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info -X brokers=localhost:9092 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  redpanda-init:
    build:
      context: ./redpanda
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-ec"]
    command: |
      echo "Creating topic client_tickets if needed..."
      rpk topic list -X brokers=redpanda:9092
    restart: "no"
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: ticket-producer
    environment:
      REDPANDA_BOOTSTRAP_SERVERS: redpanda:9092
      REDPANDA_TOPIC: client_tickets
      TICKET_PRODUCER_INTERVAL: "0.2"
      TICKET_PRODUCER_LIMIT: "20"
      TICKET_CLIENT_COUNT: "100"
    depends_on:
      redpanda:
        condition: service_healthy
    restart: "no"

  spark-processor:
    build:
      context: .
      dockerfile: spark/Dockerfile
    container_name: spark-ticket-processor
    environment:
      REDPANDA_BOOTSTRAP_SERVERS: redpanda:9092
      REDPANDA_TOPIC: client_tickets
      SPARK_OUTPUT_BASE_DIR: /app/data/output
      SPARK_CHECKPOINT_DIR: /app/data/checkpoint/ticket_stream_processor
    volumes:
      - ./data/output:/app/data/output
      - ./data/checkpoint:/app/data/checkpoint
    depends_on:
      redpanda:
        condition: service_healthy
    restart: "no"      
volumes:
  redpanda_data:
